name: flutter_radar
description: Flutter package for Radar, the leading geofencing and location tracking platform
version: 3.1.1
homepage: https://github.com/radarlabs/flutter-radar

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.radar.flutter
        pluginClass: RadarFlutterPlugin
      ios:
        pluginClass: RadarFlutterPlugin
